### PR TITLE
Remove hero-banner class from article template

### PR DESCRIPTION
**Pull request by chrisberthe**

### CODE REVIEW

**Comment by tauthomas01** [comment]
When I was working on responsive images, I added the file `hero-banner` because it was missing some style when we use "bg-set". Is there a reason why you removed it? How does it show at the moment without those styles?

**Comment by chrisberthe** [comment]
Actually, you're right - I forgot that you added the class in that PR.

Now that I think of it though, I'm on the fence as to whether we should even include the `article.image` for the article template. If we don't include it, we're able to remove the class/styles that developers will most likely modify anyways. If we do keep the image, we should at least ensure `collection.image` is being shown on the collection template - currently it isn't. And `.hero-banner` isn't a class that should be specific to the article template since it can be used throughout the theme - makes more sense as a component.

**Comment by tauthomas01** [comment]
Personally, I would show the image because the person might not know we can have images.

@t-kelly What are your thoughts?

**Comment by chrisberthe** [comment]
Take it easy :p

**Comment by t-kelly** [comment]
image

**Pull request closed without merging**
